import { useEffect, useState } from "react"
import api from "../api"

export default function Strategy() {
  const [ideas, setIdeas] = useState([])

  useEffect(() => {
    api.get("/approvals/ideas").then(r => setIdeas(r.data)).catch(() => {})
  }, [])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2">Strategy</h1>
      <p className="text-gray-500 text-sm mb-6">Ideas generated by the strategy agent, pending your approval.</p>
      {ideas.length === 0 ? (
        <p className="text-gray-600 text-sm">No pending ideas. The strategy agent runs every Monday at 7am.</p>
      ) : ideas.map(idea => (
        <div key={idea.id} className="bg-gray-900 border border-gray-800 rounded-xl p-5 mb-3">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h3 className="font-semibold mb-1">{idea.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{idea.body}</p>
            </div>
            <span className="shrink-0 bg-yellow-900 text-yellow-300 text-xs px-2 py-0.5 rounded-full">pending</span>
          </div>
          <p className="text-gray-700 text-xs mt-3 font-mono">Created {idea.created_at}</p>
        </div>
      ))}
    </div>
  )
}
