import { useEffect, useState } from "react"
import api from "../api"

export default function Strategy() {
  const [ideas, setIdeas] = useState([])
  const [error, setError] = useState(null)

  useEffect(() => {
    const load = () => api.get("/approvals/ideas").then(r => setIdeas(r.data)).catch(() => setError(true))
    load()
    const t = setInterval(load, 8000)
    return () => clearInterval(t)
  }, [])

  if (error) return <div className="text-red-600 text-sm">Could not load strategy. Is the backend running?</div>

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2 text-[#00395D]">Strategy</h1>
      <p className="text-[#6B8A9A] text-sm mb-6">Ideas generated by the strategy agent, pending your approval.</p>
      {ideas.length === 0 ? (
        <p className="text-[#6B8A9A] text-sm">No pending ideas. The strategy agent runs every Monday at 7am.</p>
      ) : ideas.map(idea => (
        <div key={idea.id} className="bg-white border border-[#E8E4D9] rounded-xl p-5 mb-3 shadow-sm">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h3 className="font-semibold mb-1 text-[#00395D]">{idea.title}</h3>
              <p className="text-[#4A5568] text-sm leading-relaxed">{idea.body}</p>
            </div>
            <span className="shrink-0 bg-[#F7CA5E]/30 text-[#00395D] text-xs px-2 py-0.5 rounded-full font-medium">pending</span>
          </div>
          <p className="text-[#6B8A9A] text-xs mt-3 font-mono">Created {idea.created_at}</p>
        </div>
      ))}
    </div>
  )
}
